// Generated by gencpp from file navigation/3dofStates.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_3DOFSTATES_H
#define NAVIGATION_MESSAGE_3DOFSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct 3dofStates_
{
  typedef 3dofStates_<ContainerAllocator> Type;

  3dofStates_()
    : N(0.0)
    , E(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , r(0.0)  {
    }
  3dofStates_(const ContainerAllocator& _alloc)
    : N(0.0)
    , E(0.0)
    , psi(0.0)
    , u(0.0)
    , v(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef double _N_type;
  _N_type N;

   typedef double _E_type;
  _E_type E;

   typedef double _psi_type;
  _psi_type psi;

   typedef double _u_type;
  _u_type u;

   typedef double _v_type;
  _v_type v;

   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::navigation::3dofStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::3dofStates_<ContainerAllocator> const> ConstPtr;

}; // struct 3dofStates_

typedef ::navigation::3dofStates_<std::allocator<void> > 3dofStates;

typedef boost::shared_ptr< ::navigation::3dofStates > 3dofStatesPtr;
typedef boost::shared_ptr< ::navigation::3dofStates const> 3dofStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::3dofStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::3dofStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::3dofStates_<ContainerAllocator1> & lhs, const ::navigation::3dofStates_<ContainerAllocator2> & rhs)
{
  return lhs.N == rhs.N &&
    lhs.E == rhs.E &&
    lhs.psi == rhs.psi &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.r == rhs.r;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::3dofStates_<ContainerAllocator1> & lhs, const ::navigation::3dofStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::3dofStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::3dofStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::3dofStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::3dofStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::3dofStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::3dofStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::3dofStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "571db7e1a9de92532ecdf36e8286b584";
  }

  static const char* value(const ::navigation::3dofStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x571db7e1a9de9253ULL;
  static const uint64_t static_value2 = 0x2ecdf36e8286b584ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::3dofStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/3dofStates";
  }

  static const char* value(const ::navigation::3dofStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::3dofStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 N\n"
"float64 E\n"
"float64 psi\n"
"float64 u\n"
"float64 v\n"
"float64 r\n"
;
  }

  static const char* value(const ::navigation::3dofStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::3dofStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.N);
      stream.next(m.E);
      stream.next(m.psi);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct 3dofStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::3dofStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::3dofStates_<ContainerAllocator>& v)
  {
    s << indent << "N: ";
    Printer<double>::stream(s, indent + "  ", v.N);
    s << indent << "E: ";
    Printer<double>::stream(s, indent + "  ", v.E);
    s << indent << "psi: ";
    Printer<double>::stream(s, indent + "  ", v.psi);
    s << indent << "u: ";
    Printer<double>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<double>::stream(s, indent + "  ", v.v);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_3DOFSTATES_H
